#!/bin/sh -e

unzip irrlicht-1.8.4.zip

for patch in *.patch; do
    patch -p0 < "$patch"
done

cd irrlicht-1.8.4/source/Irrlicht/

make NDEBUG=1 staticlib sharedlib
make DESTDIR="$1" PREFIX=/usr install

# 'make install' doesn't copy static library.
install -Dm644 ../../lib/Linux/libIrrlicht.a "$1"/usr/lib
