#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-ipv6

# seems to be problem with timestamps
sleep 1
./config.status

make all shared
make -j1 DESTDIR="$1" install install-shared
