#!/bin/sh -e

unzip tyrian21.zip

make CFLAGS=-fcommon

install -d                         "$1/usr/share/opentyrian"
install -Dm755 opentyrian          "$1/usr/share/opentyrian/opentyrian"
cp -r tyrian21/.                   "$1/usr/share/opentyrian"
install -Dm755 opentyrian-launcher "$1/usr/bin/opentyrian"
