#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -fcommon"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCDOGS_DATA_DIR=/usr/share/cdogs/ \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build
