#!/bin/sh -e

unzip cavestoryen.zip

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build build

mv build/nx* CaveStory/
mv data/*    CaveStory/data/

(cd CaveStory; ./nxextract)

mkdir -p                               "$1/usr/share/cavestory"
mkdir -p                               "$1/usr/bin"
cp -r CaveStory/.                      "$1/usr/share/nxengine"
ln -s /usr/share/nxengine/nxengine-evo "$1/usr/bin/cavestory"
