#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
	-D SOLARUS_GUI=OFF

cmake --build   build
cmake --install build

rm -rf "$1/usr/local/share/man/man6/solarus-run.6"
