#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

cp makefile.linux_amd64 makefile.machine

sed -e "s,g++,${CXX:-g++}," -i makefile.machine
sed -e "s,gcc,${CC:-gcc}," -i makefile.machine

make all3

make install \
	DEST_DIR="$1" \
	DEST_HOME=/usr \
	DEST_MAN=/usr/share/man

rm -rf "$1/usr/share/doc/"
