#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBINARY_RELEASE=ON \
    -DVERSION_NUM=1.2.1 \
    -DNONET=ON

cmake --build   build
cmake --install build
