#!/bin/sh -e

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build

unzip cavestoryen.zip
mv bin/* CaveStory/
mv data/* CaveStory/data/

(cd CaveStory; ./extract)

install -d                          "$1/usr/share/cavestory"
install -d                          "$1/usr/bin"
cp -r CaveStory/.                   "$1/usr/share/cavestory"
ln -s /usr/share/cavestory/nx       "$1/usr/bin/cavestory"
