#!/bin/sh -e

export DESTDIR="$1"

cmake -B build -S prboom2 \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DDOOMWADDIR=/usr/share/prboom-plus \
    -DCMAKE_BUILD_TYPE=Release \
    -Wno-dev

cmake --build   build
cmake --install build
