#!/bin/sh -e

mkdir build
sed -i 's|#define SHARE_DIR.*|#define SHARE_DIR "/usr/share/gzdoom/"|' src/posix/i_system.h
sed -i 's|/usr/share/games/doom|/usr/share/gzdoom|g' src/gameconfigfile.cpp
cd build &&
rm -f output_sdl/liboutput_sdl.so &&
cmake \
	-DCMAKE_BUILD_TYPE=Release \
	-DNO_FMOD=ON \
	-DNO_GTK=ON \
	-DCMAKE_INSTALL_PREFIX=/usr/ \
        -DINSTALL_PATH=bin/ \
        -DINSTALL_PK3_PATH=share/gzdoom/ \
	-DSHARE_DIR=/usr/share/gzdoom/ \
	-DINSTALL_DOCS_PATH=/usr/share/gzdoom/ \
	-DCMAKE_EXE_LINKER_FLAGS=-lfts \
	-DCMAKE_CXX_FLAGS=-Wl,-lexecinfo \
	..

make 

make DESTDIR="$1" install
