#!/bin/sh -e

# I have other solution than forcing clang.
export CC=clang
export CXX=clang++

cd FreeImage

for patch in ../*.patch; do
    patch -Np1 -i "$patch"
done

make
make DESTDIR="$1" install
