#!/bin/sh

cat <<EOF

### IMPORTANT ###
### IMPORTANT ###

Pip is invoked in the buildfile to install scons.
To avoid repeated installation, this package
can be forked with kiss-fork on your own discretion.


### IMPORTANT ###
### IMPORTANT ###
EOF
