#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DGLOBAL_DIR=/usr/share/openttd \
    -DCMAKE_INSTALL_DATADIR=share \
    -DCMAKE_INSTALL_BINDIR=bin

cmake --build   build
cmake --install build
