#!/bin/sh -e

sed -i CMakeLists.txt -e "s; -Werror;;"

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCDOGS_DATA_DIR=/usr/share/cdogs/ \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build
