#!/bin/sh -e

mkdir build/


cmake -DCMAKE_BUILD_TYPE=Release -B build/

make -C build/
ls
unzip cavestoryen.zip
ls
#cp bin/nx CaveStory/
#cp bin/extract CaveStory/
#cp -r data/ CaveStory/


install -d $1/usr/share/cavestory

cp -pr CaveStory/* $1/usr/share/cavestory

install -Dm755 bin/nx $1/usr/share/cavestory/nx
install -Dm755 bin/extract $1/usr/share/cavestory/extract
cp -r data/ $1/usr/share/cavestory/
install -Dm755 cavestory $1/usr/bin/cavestory
