#!/bin/sh -e

mkdir build/


cmake -DCMAKE_BUILD_TYPE=Release -B build/

make -C build/

unzip cavestoryen.zip

mv bin/* CaveStory/

mv data/* CaveStory/data/

(cd CaveStory; ./extract)


install -d $1/usr/share/cavestory

cp -r CaveStory/* $1/usr/share/cavestory/

install -Dm755 cavestory-launcher $1/usr/bin/cavestory
