#!/bin/sh


install -d $1/usr/share/sauerbraten/bin
install -Dm755 sauerbraten-client $1/usr/bin/sauerbraten-client
cp -pr data/ $1/usr/share/sauerbraten
cp -pr packages/ $1/usr/share/sauerbraten


cd src

make PREFIX=/usr client

make DESTDIR="$1" install

cd ..

install -D bin_unix/native_client $1/usr/share/sauerbraten/bin/linux_client

