#!/bin/sh -e

sed -e '/_XData32/s:register long:register _Xconst long:' \
	    -i src/video/x11/SDL_x11sym.h

./configure \
    --prefix=/usr \
    --disable-dbus \
    --disable-static \
    --enable-video-opengl \
    --disable-ibus
    
make
make DESTDIR="$1" install
