#!/bin/sh -e

#GCC10 fix
export CFLAGS="$CFLAGS -fcommon"

mkdir -p                  assets/installer
mv srb2kart-v101/*.kart   assets/installer/
mv srb2kart-v101/srb2.srb assets/installer/

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr/share/srb2kart \
    -DCMAKE_BUILD_TYPE=INSTALL

cmake --build   build
cmake --install build

install -Dm755  srb2kartlauncher    "$1/usr/bin/srb2kart"
