#!/bin/sh -e

#GCC10 fix
export CFLAGS="$CFLAGS -fcommon"

7z x srb2kart-v13-Installer.exe

mkdir -p    assets/installer
mv *.kart   assets/installer/
mv srb2.srb assets/installer/

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr/share/srb2kart \
    -DCMAKE_BUILD_TYPE=INSTALL

cmake --build   build
cmake --install build

install -Dm755  srb2kartlauncher    "$1/usr/bin/srb2kart"
