#!/bin/sh -e

sed -r "s/-DUSE_PVRTC|-DUSE_ETC1//g" -i Hurrican/src/Makefile

make TARGET=linux -C Hurrican/src/

rm -rf Hurrican/src/
rm Hurrican/*.exe
rm Hurrican/*.dll

install -d                      "$1/usr/share/hurrican"
install -Dm755 hurricanlauncher "$1/usr/bin/hurrican"
cp -r Hurrican/.                "$1/usr/share/hurrican"
