#!/bin/sh -e

export DESTDIR="$1"

#GCC10 fix
#export CFLAGS="$CFLAGS -fcommon"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DOSHU_DEFAULT_SKIN=minimal

cmake --build   build
cmake --install build
