#!/bin/sh -e

patch -p1 < Makefile_lncursesw.patch

make

install -d $1/usr/local/share/npush/
install -Dm755 npush $1/usr/local/share/npush/npush
cp -r levels/ $1/usr/local/share/npush/
install -Dm755 npush-launcher $1/usr/local/bin/npush
