#!/bin/sh -e

./configure \
     --disable-sdltest \
     --disable-alsatest \
     --disable-jack \
     --disable-debugger \
     --enable-threads=posix \
     --prefix=/usr

make
make DESTDIR="$1" install
