#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_TYPE=Release

cmake --build 	build

install -Dm755 build/src/crispy-doom 	"$1/usr/bin/crispy-doom"
install -Dm755 build/src/crispy-server	"$1/usr/bin/crispy-server"
install -Dm755 build/src/crispy-setup	"$1/usr/bin/crispy-setup"
