#!/bin/sh -e

for patch in *.patch; do
    patch -Np1 < "$patch"
done

cp makefile.linux_amd64 makefile.machine

make all3

make install \
    DEST_DIR="$1" \
    DEST_HOME=/usr \
    DEST_MAN=/usr/share/man

rm -rf "$1/usr/share/doc/"
