#!/bin/sh -e

unzip 6b46ca6fa8f7.zip
unzip tyrian21.zip

make -C opentyrian-opentyrian-6b46ca6fa8f7/

install -d 								"$1/usr/share/opentyrian"
install -Dm755 opentyrian-opentyrian-6b46ca6fa8f7/opentyrian 		"$1/usr/share/opentyrian/opentyrian"
cp -r tyrian21/. 							"$1/usr/share/opentyrian"
install -Dm755 opentyrian-launcher					"$1/usr/bin/opentyrian"
