#!/bin/sh -e

install -Dm644 FluidR3_GM.sf2               "$1/usr/share/soundfonts/FluidR3_GM.sf2"
install -Dm644 FluidR3_GS.sf2               "$1/usr/share/soundfonts/FluidR3_GS.sf2"
ln -s /usr/share/soundfonts/FluidR3_GM.sf2  "$1/usr/share/soundfonts/default.sf2"
