#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DSFML_USE_SYSTEM_DEPS=ON \
    -DSFML_BUILD_EXAMPLES=0 \
    -DSFML_BUILD_DOC=0 \
    -DSFML_INSTALL_PKGCONFIG_FILES=1

cmake --build   build
cmake --install build
