#!/bin/sh -e

unzip xonotic-0.8.2.zip

patch -p1 < musl-moncontrol.patch Xonotic/source/darkplaces/sys_shared.c


install -d $1/usr/share/xonotic

cp -pr Xonotic/data/ $1/usr/share/xonotic



cd Xonotic/source/darkplaces

sed -i makefile.inc \
	-e "s;^\(CPUOPTIMIZATIONS\)?=\(.*\);\1=${CFLAGS} \2;" \
	-e "s;^\(LDFLAGS_UNIXCOMMON\)=\(.*\);\1=${LDFLAGS} \2;"

make SDL_CONFIG=sdl2-config DP_FS_BASEDIR=/usr/share/xonotic/ DP_LINK_TO_LIBJPEG=1 sdl-release

#cd ${wrksrc}/source/d0_blind_id
#	autoreconf -fi
#	./configure --prefix=/usr --disable-rijndael
#	make ${makejobs}
#cant perform this because of missing autoreconf. lets see if it matters
install -Dm755 darkplaces-sdl $1/usr/bin/xonotic-sdl




