#!/bin/sh -e


export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DDYN_FLUIDSYNTH=OFF \
    -DDYN_MPG123=OFF \
    -DDYN_SNDFILE=OFF

cmake --build   build
cmake --install build
