#!/bin/sh -e

./configure

make

install -Dm755 launcher.sh    "$1/usr/bin/dustracing"
install -Dm755 dustrac-game   "$1/usr/share/dustracing/dustrac-game"
install -Dm755 dustrac-editor "$1/usr/share/dustracing/dustrac-editor"
cp -r data/                   "$1/usr/share/dustracing/"
