#!/bin/sh -e

# look in home directory for data files
sed 's|"/."|"/.openjazz/"|' -i src/main.cpp

export CPPFLAGS="$CPPFLAGS -DDATAPATH=\\\"/usr/share/openjazz/\\\" -DHOMEDIR"

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

mv game "$1/usr/share/openjazz/shareware"
