#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_NLS=OFF \
    -DENABLE_DOCS=OFF \
    -DENABLE_DISCORD=OFF \
    -DWZ_ENABLE_WARNINGS_AS_ERRORS=OFF

cmake --build   build
cmake --install build
