#!/bin/sh -e

export LDFLAGS="$LDFLAGS -lexecinfo"

make WITH_SYSTEMWIDE=yes WITH_SYSTEMDIR=/usr/lib/yquake2

install -Dm644 release/ref_gl3.so     "$1/usr/lib/yquake2/ref_gl3.so"
install -Dm644 release/ref_gl1.so     "$1/usr/lib/yquake2/ref_gl1.so"
install -Dm644 release/ref_soft.so    "$1/usr/lib/yquake2/ref_soft.so"
install -Dm644 release/baseq2/game.so "$1/usr/lib/yquake2/baseq2/game.so"
install -Dm644 stuff/yq2.cfg          "$1/usr/share/yquake2/yq2.cfg"
install -Dm755 release/quake2         "$1/usr/lib/yquake2/quake2"
install -Dm755 release/q2ded          "$1/usr/lib/yquake2/q2ded"

# Binaries need to be in the same directory as the .so files - create a link.
mkdir -p "$1/usr/bin"
ln -s ../lib/yquake2/quake2           "$1/usr/bin/quake2"
ln -s ../lib/yquake2/q2ded            "$1/usr/bin/q2ded"
