#!/bin/sh -e

install -D /usr/include/curses.h $1/usr/include/cursesw.h
#ohoh dirty hack :\
patch -p1 < Makefile_lncursesw.patch

make PREFIX=/usr
install -d $1/usr/share/pacvim-maps
cp -r maps/ $1/usr/share/pacvim-maps
install -Dm755  pacvim $1/usr/bin/pacvim

